version: '3.5'

services:
  node:
    container_name: node
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9001
      - 4040
    networks: 
      - web
    command: pm2-runtime start /var/node-app/docker/build-files/ecosystem.config.js --env production && pm2 logs
    volumes: 
      - build-volume:/var/node-app
    labels:
      # watcher
      - traefik.watcher.frontend=node
      - traefik.http.services.watcher=node
      - traefik.http.routers.watcher.rule=Host(`watcher9001.${HOST_DOMAIN}`)
      - traefik.http.routers.watcher.entrypoints=watcher
      # node
      - traefik.node.port=4040
      - traefik.node.frontend=node
      - traefik.http.routers.node.rule=HostRegexp(`${HOST_DOMAIN}`, `{subdomain:[a-z]+}.${HOST_DOMAIN}`)
      - traefik.http.routers.node.entrypoints=web

  traefik:
    container_name: traefik
    build:
      context: .
      dockerfile: Traefik.Dockerfile
    ports:
      - "80:80"
      - "443:433"
      - "8080:8080"
    networks: 
      - web
    command: 
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=true
      - --entrypoints.web.address=:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    
  whoami:
    image: containous/whoami
    container_name: whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.${HOST_DOMAIN}`)"
      - "traefik.http.routers.whoami.entrypoints=web"

networks:
  web:
    external: true

volumes:
  build-volume: