version: '3.5'

services:
  node:
    container_name: node
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "5432:5432"
    networks: 
      - internal
    command: pm2-runtime start /var/node-app/docker/build-files/ecosystem.config.js --env production
    # command: pm2-runtime start /var/node-app/server/dist/index.js --env production

networks:
  internal:
    driver: bridge

# volumes:
