version: '3.5'

services:
  node:
    container_name: node
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"

networks:
  postgres:
    driver: bridge

# volumes:
