version: '3.5'

services:
  node:
    container_name: node
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    networks: 
      - internal
    command: pm2-runtime start /var/node-app/docker/build-files/ecosystem.config.js --env production
  
  traefik:
    container_name: traefik
    build:
      context: .
      dockerfile: Traefik.Dockerfile
    ports:
      - "80:80"
      - "8080:8080"
    networks: 
      - internal
    command: 
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.web.address=:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    
  whoami:
    image: containous/whoami
    container_name: whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"

networks:
  internal:
    driver: bridge

# volumes:
