version: '3.5'

services:
  node:
    container_name: node
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks: 
      - internal
    command: pm2-runtime start /var/node-app/ecosystem.config.js --env production
    # command: pm2 start /var/node-app/ --env production

networks:
  internal:
    driver: bridge

# volumes:
