[providers.docker]
  # endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = true
  network = "web"

[http.routers]
  [http.routers.node]
    rule = "Host(`localhost`)"
    service = "node"

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.traefik]
    address = ":8080"  