api:
  dashboard: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
  http:
    address: ":8080"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: true

# certificatesResolvers:
#   http:
#     acme:
#       email: email@example.com
#       storage: acme.json
#       httpChallenge:
#         entryPoint: http